# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji
  
# Site settings
title: "oronaldosantos blog"
description: > # this means to ignore newlines until "email:"
   A Jekyll theme - Medium inspired

email: oronaldosantos@gmail.com
#blog logo
logo: "https://fbcdn-profile-a.akamaihd.net/hprofile-ak-xfp1/v/t1.0-1/c32.36.576.576/s160x160/923490_10152017874547098_2084617747_n.jpg?oh=f77c318c001c46c4f95db72f5894500c&oe=5668E1FB&__gda__=1450119366_8b0ab456895cdbb4f4cd8f76f5e674e7"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Ronaldo Bitencourt'
author: 'Ronaldo Bitencourt'
author_image: "https://fbcdn-profile-a.akamaihd.net/hprofile-ak-xfp1/v/t1.0-1/c32.36.576.576/s160x160/923490_10152017874547098_2084617747_n.jpg?oh=f77c318c001c46c4f95db72f5894500c&oe=5668E1FB&__gda__=1450119366_8b0ab456895cdbb4f4cd8f76f5e674e7"

paginate:	5

url: "http://oronaldosantos.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@oronaldosantos'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/oronaldosantos
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/oronaldosantos
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/oronaldosantos
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
